import { ProductSchema, getProductImage, getProductName, productSchema } from "./product"

describe("openFoodFacts", () => {
  test("should return a valid name if it exists", () => {
    const product = productSchema.parse(aitoResponse)
    const name = getProductName(product, "fr")
    expect(name).toBe("Oat drink natural")
  })

  test("should return generic product name if localized doesn't exists", () => {
    const product = productSchema.parse(aitoResponse)
    const name = getProductName(product, "da")
    expect(name).toBe("Aito Oat Drink Natural")
  })

  test("should return the localized image if it exists", () => {
    const product = productSchema.parse(aitoResponse)
    const image = getProductImage(product, "front", "display", "fr")
    expect(image).toBe("https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.400.jpg")
  })

  test("use first image when none could be found", () => {
    const product = productSchema.parse(aitoResponse)
    const image = getProductImage(product, "front", "display", "da")
    expect(image).toBe("https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.400.jpg")
  })

  test("should parse the json", () => {
    const product = productSchema.parse(aitoResponse)

    const expected: ProductSchema = {
      code: "6410222005402",
      product_name: "Aito Oat Drink Natural",
      product_name_localized: {
        da: "",
        de: "Aito Oat Drink Natural",
        en: "",
        fr: "Oat drink natural",
      },
      selected_images: {
        front: {
          display: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.400.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.400.jpg",
          },
          small: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.200.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.200.jpg",
          },
          thumb: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.100.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.100.jpg",
          },
        },
        ingredients: {
          display: {
            da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.400.jpg",
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.400.jpg",
            en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.400.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.400.jpg",
          },
          small: {
            da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.200.jpg",
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.200.jpg",
            en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.200.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.200.jpg",
          },
          thumb: {
            da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.100.jpg",
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.100.jpg",
            en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.100.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.100.jpg",
          },
        },
        nutrition: {
          display: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.400.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.400.jpg",
          },
          small: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.200.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.200.jpg",
          },
          thumb: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.100.jpg",
            fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.100.jpg",
          },
        },
        packaging: {
          display: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.400.jpg",
          },
          small: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.200.jpg",
          },
          thumb: {
            de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.100.jpg",
          },
        },
      },
    }

    expect(product).toEqual(expected)
    const localizedName = product.product_name_localized["de"]
    expect(localizedName).toBe("Aito Oat Drink Natural")
  })
})

const aitoResponse = {
  _id: "6410222005402",
  _keywords: [
    "aito",
    "alternative",
    "and",
    "beverage",
    "cereal",
    "cereal-based",
    "dairy",
    "drink",
    "eu",
    "fazer",
    "fi-eko-201",
    "finland",
    "food",
    "fsc",
    "milk",
    "mix",
    "natural",
    "oat",
    "oat-based",
    "organic",
    "plant-based",
    "potatoe",
    "product",
    "substitute",
    "their",
  ],
  added_countries_tags: [],
  additives_n: 0,
  additives_old_n: 0,
  additives_old_tags: [],
  additives_original_tags: [],
  additives_tags: [],
  allergens: "en:gluten",
  allergens_from_ingredients: "Vollkornhafer",
  allergens_from_user: "(en) en:gluten",
  allergens_hierarchy: ["en:gluten"],
  allergens_lc: "en",
  allergens_tags: ["en:gluten"],
  amino_acids_tags: [],
  brands: "Fazer,Aito",
  brands_tags: ["fazer", "aito"],
  categories:
    "Pflanzliche Lebensmittel und Getränke, Getränke, Pflanzliche Lebensmittel, Getreide und Kartoffeln, en:Dairy substitutes, Getreideprodukte, Milchersatz, Pflanzliche Getränke, Pflanzenmilch, Getreidemilch, Hafermilch",
  categories_hierarchy: [
    "en:plant-based-foods-and-beverages",
    "en:beverages",
    "en:plant-based-foods",
    "en:cereals-and-potatoes",
    "en:dairy-substitutes",
    "en:cereals-and-their-products",
    "en:milk-substitutes",
    "en:plant-based-beverages",
    "en:plant-based-milk-alternatives",
    "en:cereal-based-drinks",
    "en:oat-based-drinks",
  ],
  categories_lc: "de",
  categories_old:
    "Plant-based foods and beverages,Beverages,Plant-based foods,Cereals and potatoes,Dairy substitutes,Cereals and their products,Milk substitutes,Plant-based beverages,Plant-based milk alternatives,Cereal-based drinks,Oat-based drinks",
  categories_properties: {
    "agribalyse_food_code:en": "18905",
    "agribalyse_proxy_food_code:en": "18905",
    "ciqual_food_code:en": "18905",
  },
  categories_properties_tags: [
    "all-products",
    "categories-known",
    "agribalyse-food-code-18905",
    "agribalyse-food-code-known",
    "agribalyse-proxy-food-code-18905",
    "agribalyse-proxy-food-code-known",
    "ciqual-food-code-18905",
    "ciqual-food-code-known",
    "agribalyse-known",
    "agribalyse-18905",
  ],
  categories_tags: [
    "en:plant-based-foods-and-beverages",
    "en:beverages",
    "en:plant-based-foods",
    "en:cereals-and-potatoes",
    "en:dairy-substitutes",
    "en:cereals-and-their-products",
    "en:milk-substitutes",
    "en:plant-based-beverages",
    "en:plant-based-milk-alternatives",
    "en:cereal-based-drinks",
    "en:oat-based-drinks",
  ],
  checked: "on",
  checkers_tags: ["moon-rabbit"],
  cities_tags: [],
  code: "6410222005402",
  codes_tags: [
    "code-13",
    "6410222005xxx",
    "641022200xxxx",
    "64102220xxxxx",
    "6410222xxxxxx",
    "641022xxxxxxx",
    "64102xxxxxxxx",
    "6410xxxxxxxxx",
    "641xxxxxxxxxx",
    "64xxxxxxxxxxx",
    "6xxxxxxxxxxxx",
  ],
  compared_to_category: "en:oat-based-drinks",
  complete: 0,
  completeness: 0.9,
  correctors_tags: ["grumpf", "isabel626", "worldtest", "moon-rabbit", "roboto-app"],
  countries: "Germany",
  countries_hierarchy: ["en:germany"],
  countries_lc: "en",
  countries_tags: ["en:germany"],
  created_t: 1675618568,
  creator: "kiliweb",
  data_quality_bugs_tags: [],
  data_quality_errors_tags: [],
  data_quality_info_tags: [
    "en:packaging-data-incomplete",
    "en:ecoscore-extended-data-not-computed",
    "en:food-groups-1-known",
    "en:food-groups-2-known",
    "en:food-groups-3-unknown",
  ],
  data_quality_tags: [
    "en:packaging-data-incomplete",
    "en:ecoscore-extended-data-not-computed",
    "en:food-groups-1-known",
    "en:food-groups-2-known",
    "en:food-groups-3-unknown",
    "en:ingredients-percent-analysis-not-ok",
  ],
  data_quality_warnings_tags: ["en:ingredients-percent-analysis-not-ok"],
  data_sources: "App - Yuka, Apps",
  data_sources_tags: ["app-yuka", "apps"],
  debug_param_sorted_langs: ["de", "da", "en", "fr"],
  ecoscore_data: {
    adjustments: {
      origins_of_ingredients: {
        aggregated_origins: [
          {
            epi_score: "90",
            origin: "en:finland",
            percent: 100,
            transportation_score: null,
          },
        ],
        epi_score: 90,
        epi_value: 4,
        origins_from_categories: ["en:unknown"],
        origins_from_origins_field: ["en:finland"],
        transportation_score: 0,
        transportation_scores: {
          ad: 37,
          al: 24,
          at: 13,
          ax: 85,
          ba: 2,
          be: 70,
          bg: 4,
          ch: 20,
          cy: 22,
          cz: 13,
          de: 6,
          dk: 43,
          dz: 28,
          ee: 96,
          eg: 17,
          es: 45,
          fi: 100,
          fo: 68,
          fr: 42,
          gg: 53,
          gi: 55,
          gr: 32,
          hr: 13,
          hu: 3,
          ie: 69,
          il: 17,
          im: 44,
          is: 47,
          it: 28,
          je: 51,
          lb: 22,
          li: 22,
          lt: 67,
          lu: 61,
          lv: 80,
          ly: 39,
          ma: 42,
          mc: 43,
          md: 6,
          me: 20,
          mk: 11,
          mt: 39,
          nl: 71,
          no: 45,
          pl: 40,
          ps: 25,
          pt: 50,
          ro: 14,
          rs: 1,
          se: 68,
          si: 16,
          sj: 54,
          sk: 20,
          sm: 21,
          sy: 9,
          tn: 43,
          tr: 0,
          ua: 20,
          uk: 64,
          us: 0,
          va: 6,
          world: 0,
          xk: 10,
        },
        transportation_value: 0,
        transportation_values: {
          ad: 6,
          al: 4,
          at: 2,
          ax: 13,
          ba: 0,
          be: 11,
          bg: 1,
          ch: 3,
          cy: 3,
          cz: 2,
          de: 1,
          dk: 6,
          dz: 4,
          ee: 14,
          eg: 3,
          es: 7,
          fi: 15,
          fo: 10,
          fr: 6,
          gg: 8,
          gi: 8,
          gr: 5,
          hr: 2,
          hu: 0,
          ie: 10,
          il: 3,
          im: 7,
          is: 7,
          it: 4,
          je: 8,
          lb: 3,
          li: 3,
          lt: 10,
          lu: 9,
          lv: 12,
          ly: 6,
          ma: 6,
          mc: 6,
          md: 1,
          me: 3,
          mk: 2,
          mt: 6,
          nl: 11,
          no: 7,
          pl: 6,
          ps: 4,
          pt: 8,
          ro: 2,
          rs: 0,
          se: 10,
          si: 2,
          sj: 8,
          sk: 3,
          sm: 3,
          sy: 1,
          tn: 6,
          tr: 0,
          ua: 3,
          uk: 10,
          us: 0,
          va: 1,
          world: 0,
          xk: 2,
        },
        value: 4,
        values: {
          ad: 10,
          al: 8,
          at: 6,
          ax: 17,
          ba: 4,
          be: 15,
          bg: 5,
          ch: 7,
          cy: 7,
          cz: 6,
          de: 5,
          dk: 10,
          dz: 8,
          ee: 18,
          eg: 7,
          es: 11,
          fi: 19,
          fo: 14,
          fr: 10,
          gg: 12,
          gi: 12,
          gr: 9,
          hr: 6,
          hu: 4,
          ie: 14,
          il: 7,
          im: 11,
          is: 11,
          it: 8,
          je: 12,
          lb: 7,
          li: 7,
          lt: 14,
          lu: 13,
          lv: 16,
          ly: 10,
          ma: 10,
          mc: 10,
          md: 5,
          me: 7,
          mk: 6,
          mt: 10,
          nl: 15,
          no: 11,
          pl: 10,
          ps: 8,
          pt: 12,
          ro: 6,
          rs: 4,
          se: 14,
          si: 6,
          sj: 12,
          sk: 7,
          sm: 7,
          sy: 5,
          tn: 10,
          tr: 4,
          ua: 7,
          uk: 14,
          us: 4,
          va: 5,
          world: 4,
          xk: 6,
        },
      },
      packaging: {
        non_recyclable_and_non_biodegradable_materials: 0,
        packagings: [
          {
            ecoscore_material_score: 62,
            ecoscore_shape_ratio: 1,
            material: "en:tetra-pak",
            number_of_units: 1,
            shape: "en:brick",
          },
          {
            ecoscore_material_score: 50,
            ecoscore_shape_ratio: 0.1,
            material: "en:hdpe-2-high-density-polyethylene",
            material_shape: "en:hdpe-2-high-density-polyethylene.en:bottle-cap",
            non_recyclable_and_non_biodegradable: "no",
            number_of_units: 1,
            shape: "en:bottle-cap",
          },
        ],
        score: 57,
        value: -4,
      },
      production_system: {
        labels: ["en:eu-organic"],
        value: 15,
      },
      threatened_species: {},
    },
    agribalyse: {
      agribalyse_food_code: "18905",
      agribalyse_proxy_food_code: "18905",
      co2_agriculture: 0.13722151,
      co2_consumption: 0,
      co2_distribution: 0.014644818,
      co2_packaging: 0.10010411,
      co2_processing: 0.15081878,
      co2_total: 0.536418898,
      co2_transportation: 0.13362968,
      code: "18905",
      dqr: "2.23",
      ef_agriculture: 0.0320651,
      ef_consumption: 0,
      ef_distribution: 0.0042592639,
      ef_packaging: 0.0099703815,
      ef_processing: 0.020535013,
      ef_total: 0.0777455534,
      ef_transportation: 0.010915795,
      is_beverage: 1,
      name_en: "Oat-based drink, plain, prepacked",
      name_fr: "Boisson à base d'avoine, nature",
      score: 72,
      version: "3.1",
    },
    grade: "a",
    grades: {
      ad: "a",
      al: "a",
      at: "a",
      ax: "a",
      ba: "a",
      be: "a",
      bg: "a",
      ch: "a",
      cy: "a",
      cz: "a",
      de: "a",
      dk: "a",
      dz: "a",
      ee: "a",
      eg: "a",
      es: "a",
      fi: "a",
      fo: "a",
      fr: "a",
      gg: "a",
      gi: "a",
      gr: "a",
      hr: "a",
      hu: "a",
      ie: "a",
      il: "a",
      im: "a",
      is: "a",
      it: "a",
      je: "a",
      lb: "a",
      li: "a",
      lt: "a",
      lu: "a",
      lv: "a",
      ly: "a",
      ma: "a",
      mc: "a",
      md: "a",
      me: "a",
      mk: "a",
      mt: "a",
      nl: "a",
      no: "a",
      pl: "a",
      ps: "a",
      pt: "a",
      ro: "a",
      rs: "a",
      se: "a",
      si: "a",
      sj: "a",
      sk: "a",
      sm: "a",
      sy: "a",
      tn: "a",
      tr: "a",
      ua: "a",
      uk: "a",
      us: "a",
      va: "a",
      world: "a",
      xk: "a",
    },
    previous_data: {
      agribalyse: {
        warning: "missing_agribalyse_match",
      },
      grade: null,
      score: null,
    },
    score: 87,
    scores: {
      ad: 93,
      al: 91,
      at: 89,
      ax: 97,
      ba: 87,
      be: 97,
      bg: 88,
      ch: 90,
      cy: 90,
      cz: 89,
      de: 88,
      dk: 93,
      dz: 91,
      ee: 97,
      eg: 90,
      es: 94,
      fi: 97,
      fo: 97,
      fr: 93,
      gg: 95,
      gi: 95,
      gr: 92,
      hr: 89,
      hu: 87,
      ie: 97,
      il: 90,
      im: 94,
      is: 94,
      it: 91,
      je: 95,
      lb: 90,
      li: 90,
      lt: 97,
      lu: 96,
      lv: 97,
      ly: 93,
      ma: 93,
      mc: 93,
      md: 88,
      me: 90,
      mk: 89,
      mt: 93,
      nl: 97,
      no: 94,
      pl: 93,
      ps: 91,
      pt: 95,
      ro: 89,
      rs: 87,
      se: 97,
      si: 89,
      sj: 95,
      sk: 90,
      sm: 90,
      sy: 88,
      tn: 93,
      tr: 87,
      ua: 90,
      uk: 97,
      us: 87,
      va: 88,
      world: 87,
      xk: 89,
    },
    status: "known",
  },
  ecoscore_grade: "a",
  ecoscore_score: 87,
  ecoscore_tags: ["a"],
  editors_tags: [
    "grumpf",
    "isabel626",
    "kiliweb",
    "moon-rabbit",
    "roboto-app",
    "worldtest",
    "yuka.sY2b0xO6T85zoF3NwEKvlmxMXYLf82LpPSb5p1aByOitH6z6Qt9x-prdN6g",
  ],
  emb_codes: "FSC-C014047",
  emb_codes_tags: ["fsc-c014047"],
  entry_dates_tags: ["2023-02-05", "2023-02", "2023"],
  expiration_date: "",
  food_groups: "en:plant-based-milk-substitutes",
  food_groups_tags: ["en:beverages", "en:plant-based-milk-substitutes"],
  generic_name: "",
  generic_name_da: "",
  generic_name_de: "",
  generic_name_en: "",
  generic_name_fr: "",
  id: "6410222005402",
  image_front_small_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.200.jpg",
  image_front_thumb_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.100.jpg",
  image_front_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.400.jpg",
  image_ingredients_small_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.200.jpg",
  image_ingredients_thumb_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.100.jpg",
  image_ingredients_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.400.jpg",
  image_nutrition_small_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.200.jpg",
  image_nutrition_thumb_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.100.jpg",
  image_nutrition_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.400.jpg",
  image_packaging_small_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.200.jpg",
  image_packaging_thumb_url:
    "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.100.jpg",
  image_packaging_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.400.jpg",
  image_small_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.200.jpg",
  image_thumb_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.100.jpg",
  image_url: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.400.jpg",
  images: {
    "1": {
      sizes: {
        "100": {
          h: 100,
          w: 34,
        },
        "400": {
          h: 400,
          w: 137,
        },
        full: {
          h: 1200,
          w: 410,
        },
      },
      uploaded_t: 1675618570,
      uploader: "kiliweb",
    },
    "2": {
      sizes: {
        "100": {
          h: 74,
          w: 100,
        },
        "400": {
          h: 296,
          w: 400,
        },
        full: {
          h: 799,
          w: 1081,
        },
      },
      uploaded_t: 1675618571,
      uploader: "kiliweb",
    },
    "3": {
      sizes: {
        "100": {
          h: 100,
          w: 100,
        },
        "400": {
          h: 400,
          w: 400,
        },
        full: {
          h: 750,
          w: 750,
        },
      },
      uploaded_t: 1681394525,
      uploader: "grumpf",
    },
    "4": {
      sizes: {
        "100": {
          h: 100,
          w: 75,
        },
        "400": {
          h: 400,
          w: 300,
        },
        full: {
          h: 1000,
          w: 750,
        },
      },
      uploaded_t: 1681394528,
      uploader: "grumpf",
    },
    "5": {
      sizes: {
        "100": {
          h: 95,
          w: 100,
        },
        "400": {
          h: 379,
          w: 400,
        },
        full: {
          h: 673,
          w: 711,
        },
      },
      uploaded_t: 1681394530,
      uploader: "grumpf",
    },
    "6": {
      sizes: {
        "100": {
          h: 100,
          w: 75,
        },
        "400": {
          h: 400,
          w: 299,
        },
        full: {
          h: 4000,
          w: 2992,
        },
      },
      uploaded_t: 1706440660,
      uploader: "moon-rabbit",
    },
    "7": {
      sizes: {
        "100": {
          h: 100,
          w: 75,
        },
        "400": {
          h: 400,
          w: 299,
        },
        full: {
          h: 4000,
          w: 2992,
        },
      },
      uploaded_t: 1706440702,
      uploader: "moon-rabbit",
    },
    "8": {
      sizes: {
        "100": {
          h: 100,
          w: 75,
        },
        "400": {
          h: 400,
          w: 299,
        },
        full: {
          h: 4000,
          w: 2992,
        },
      },
      uploaded_t: 1706440747,
      uploader: "moon-rabbit",
    },
    front_de: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "1059x3357-989-255",
      imgid: "6",
      normalize: "false",
      rev: "19",
      sizes: {
        "100": {
          h: 100,
          w: 32,
        },
        "200": {
          h: 200,
          w: 63,
        },
        "400": {
          h: 400,
          w: 126,
        },
        full: {
          h: 3357,
          w: 1059,
        },
      },
      white_magic: "false",
      x1: "989.0765013031612",
      x2: "2048.679150309784",
      y1: "255.26802113514074",
      y2: "3612.5831856632867",
    },
    front_fr: {
      angle: 0,
      coordinates_image_size: "full",
      geometry: "0x0--1--1",
      imgid: "1",
      normalize: null,
      rev: "3",
      sizes: {
        "100": {
          h: 100,
          w: 34,
        },
        "200": {
          h: 200,
          w: 68,
        },
        "400": {
          h: 400,
          w: 137,
        },
        full: {
          h: 1200,
          w: 410,
        },
      },
      white_magic: null,
      x1: "-1",
      x2: "-1",
      y1: "-1",
      y2: "-1",
    },
    ingredients_da: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "576x159-862-1798",
      imgid: "7",
      normalize: "false",
      rev: "26",
      sizes: {
        "100": {
          h: 28,
          w: 100,
        },
        "200": {
          h: 55,
          w: 200,
        },
        "400": {
          h: 110,
          w: 400,
        },
        full: {
          h: 159,
          w: 576,
        },
      },
      white_magic: "false",
      x1: "862.4024807759467",
      x2: "1438.1689368241668",
      y1: "1798.7636540899214",
      y2: "1957.0989545607408",
    },
    ingredients_de: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "651x243-807-340",
      imgid: "7",
      normalize: "false",
      rev: "21",
      sizes: {
        "100": {
          h: 37,
          w: 100,
        },
        "200": {
          h: 75,
          w: 200,
        },
        "400": {
          h: 149,
          w: 400,
        },
        full: {
          h: 243,
          w: 651,
        },
      },
      white_magic: "false",
      x1: "807.9263806879915",
      x2: "1458.4043142558721",
      y1: "340.6602467922186",
      y2: "583.9055547651077",
    },
    ingredients_en: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "569x160-864-1431",
      imgid: "7",
      normalize: "false",
      rev: "25",
      sizes: {
        "100": {
          h: 28,
          w: 100,
        },
        "200": {
          h: 56,
          w: 200,
        },
        "400": {
          h: 112,
          w: 400,
        },
        full: {
          h: 160,
          w: 569,
        },
      },
      white_magic: "false",
      x1: "864.6609836603632",
      x2: "1433.4033441606737",
      y1: "1431.8031159457782",
      y2: "1591.3283998603065",
    },
    ingredients_fr: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "673x237-831-884",
      imgid: "7",
      normalize: "false",
      rev: "24",
      sizes: {
        "100": {
          h: 35,
          w: 100,
        },
        "200": {
          h: 70,
          w: 200,
        },
        "400": {
          h: 141,
          w: 400,
        },
        full: {
          h: 237,
          w: 673,
        },
      },
      white_magic: "false",
      x1: "831.350743982176",
      x2: "1504.7358588414477",
      y1: "884.1261705815398",
      y2: "1121.057573533216",
    },
    nutrition_de: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "694x1027-1498-376",
      imgid: "7",
      normalize: "false",
      rev: "23",
      sizes: {
        "100": {
          h: 100,
          w: 68,
        },
        "200": {
          h: 200,
          w: 135,
        },
        "400": {
          h: 400,
          w: 270,
        },
        full: {
          h: 1027,
          w: 694,
        },
      },
      white_magic: "false",
      x1: "1498.4775321909924",
      x2: "2192.4003708188898",
      y1: "376.8074086170323",
      y2: "1403.813242122827",
    },
    nutrition_fr: {
      angle: 0,
      coordinates_image_size: "full",
      geometry: "0x0--1--1",
      imgid: "2",
      normalize: null,
      rev: "5",
      sizes: {
        "100": {
          h: 74,
          w: 100,
        },
        "200": {
          h: 148,
          w: 200,
        },
        "400": {
          h: 296,
          w: 400,
        },
        full: {
          h: 799,
          w: 1081,
        },
      },
      white_magic: null,
      x1: "-1",
      x2: "-1",
      y1: "-1",
      y2: "-1",
    },
    packaging_de: {
      angle: "0",
      coordinates_image_size: "full",
      geometry: "511x978-897-2443",
      imgid: "7",
      normalize: "false",
      rev: "27",
      sizes: {
        "100": {
          h: 100,
          w: 52,
        },
        "200": {
          h: 200,
          w: 104,
        },
        "400": {
          h: 400,
          w: 209,
        },
        full: {
          h: 978,
          w: 511,
        },
      },
      white_magic: "false",
      x1: "897.4063449884882",
      x2: "1408.9767512643575",
      y1: "2443.0354036242757",
      y2: "3421.5162668796565",
    },
  },
  informers_tags: [
    "yuka.sY2b0xO6T85zoF3NwEKvlmxMXYLf82LpPSb5p1aByOitH6z6Qt9x-prdN6g",
    "kiliweb",
    "moon-rabbit",
    "grumpf",
    "roboto-app",
  ],
  ingredients: [
    {
      has_sub_ingredients: "yes",
      id: "en:oat-base",
      percent_estimate: 50,
      rank: 1,
      text: "Haferbasis",
    },
    {
      ciqual_food_code: "11058",
      id: "en:salt",
      percent_estimate: 50,
      rank: 2,
      text: "Salz",
      vegan: "yes",
      vegetarian: "yes",
    },
    {
      ciqual_food_code: "18066",
      id: "en:water",
      percent_estimate: 25,
      text: "Wasser",
      vegan: "yes",
      vegetarian: "yes",
    },
    {
      id: "de:bio",
      labels: "en:organic",
      percent_estimate: 12.5,
      text: "Bio",
    },
    {
      ciqual_food_code: "9310",
      id: "en:wholemeal-oat",
      percent: 12,
      percent_estimate: 12.5,
      text: "Vollkornhafer",
      vegan: "yes",
      vegetarian: "yes",
    },
  ],
  ingredients_analysis: {
    "en:palm-oil-content-unknown": ["de:bio"],
    "en:vegan-status-unknown": ["en:oat-base", "de:bio"],
    "en:vegetarian-status-unknown": ["en:oat-base", "de:bio"],
  },
  ingredients_analysis_tags: ["en:palm-oil-content-unknown", "en:vegan-status-unknown", "en:vegetarian-status-unknown"],
  ingredients_from_or_that_may_be_from_palm_oil_n: 0,
  ingredients_from_palm_oil_n: 0,
  ingredients_from_palm_oil_tags: [],
  ingredients_hierarchy: ["en:oat-base", "en:salt", "en:water", "de:bio", "en:wholemeal-oat", "en:cereal", "en:oat"],
  ingredients_lc: "de",
  ingredients_n: 5,
  ingredients_n_tags: ["5", "1-10"],
  ingredients_original_tags: ["en:oat-base", "en:salt", "en:water", "de:bio", "en:wholemeal-oat"],
  ingredients_percent_analysis: -1,
  ingredients_tags: ["en:oat-base", "en:salt", "en:water", "de:bio", "en:wholemeal-oat", "en:cereal", "en:oat"],
  ingredients_text: "Haferbasis (Wasser, Bio - Vollkornhafer 12 %), Salz.",
  ingredients_text_da: "Havrebase (vand, økologisk fuldkornshavre 12 %), salt.",
  ingredients_text_de: "Haferbasis (Wasser, Bio - Vollkornhafer 12 %), Salz.",
  ingredients_text_en: "Oat base (water, organic whole grain oat 12 %), salt.",
  ingredients_text_fr: "Base d'avoine (eau, avoine complète biologique 12 %), sel.",
  ingredients_text_with_allergens: 'Haferbasis (Wasser, Bio - <span class="allergen">Vollkornhafer</span> 12 %), Salz.',
  ingredients_text_with_allergens_da: "Havrebase (vand, økologisk fuldkornshavre 12 %), salt.",
  ingredients_text_with_allergens_de:
    'Haferbasis (Wasser, Bio - <span class="allergen">Vollkornhafer</span> 12 %), Salz.',
  ingredients_text_with_allergens_en: "Oat base (water, organic whole grain oat 12 %), salt.",
  ingredients_text_with_allergens_fr: "Base d'avoine (eau, avoine complète biologique 12 %), sel.",
  ingredients_that_may_be_from_palm_oil_n: 0,
  ingredients_that_may_be_from_palm_oil_tags: [],
  ingredients_with_specified_percent_n: 1,
  ingredients_with_specified_percent_sum: 12,
  ingredients_with_unspecified_percent_n: 3,
  ingredients_with_unspecified_percent_sum: 87.5,
  ingredients_without_ciqual_codes: ["de:bio", "en:oat-base"],
  ingredients_without_ciqual_codes_n: 2,
  interface_version_created: "20150316.jqm2",
  interface_version_modified: "20150316.jqm2",
  known_ingredients_n: 6,
  labels: "Bio, EU-Öko-Verordnung, FI-EKO-201, FSC, FSC Mix",
  labels_hierarchy: ["en:organic", "en:eu-organic", "en:fi-eko-201", "en:fsc", "en:fsc-mix"],
  labels_lc: "de",
  labels_old: "Organic, EU Organic, FSC, FSC Mix, en:fi-eko-201",
  labels_tags: ["en:organic", "en:eu-organic", "en:fi-eko-201", "en:fsc", "en:fsc-mix"],
  lang: "de",
  languages: {
    "en:danish": 2,
    "en:english": 2,
    "en:french": 5,
    "en:german": 5,
  },
  languages_codes: {
    da: 2,
    de: 5,
    en: 2,
    fr: 5,
  },
  languages_hierarchy: ["en:danish", "en:english", "en:french", "en:german"],
  languages_tags: ["en:danish", "en:english", "en:french", "en:german", "en:4", "en:multilingual"],
  last_check_dates_tags: ["2024-01-28", "2024-01", "2024"],
  last_checked_t: 1706441073,
  last_checker: "moon-rabbit",
  last_edit_dates_tags: ["2024-01-28", "2024-01", "2024"],
  last_editor: "roboto-app",
  last_image_dates_tags: ["2024-01-28", "2024-01", "2024"],
  last_image_t: 1706440748,
  last_modified_by: "roboto-app",
  last_modified_t: 1706442355,
  last_updated_t: 1707876055,
  lc: "de",
  link: "",
  main_countries_tags: [],
  manufacturing_places: "",
  manufacturing_places_tags: [],
  max_imgid: "8",
  minerals_tags: [],
  misc_tags: [
    "en:packagings-number-of-components-2",
    "en:main-countries-old-product-without-scans-in-2020",
    "en:some-ingredients-with-specified-percent",
    "en:nutrition-no-fiber",
    "en:nutriscore-computed",
    "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
    "en:nutrition-no-fiber-or-fruits-vegetables-nuts",
    "en:nutrition-fruits-vegetables-legumes-estimate-from-ingredients",
    "en:nutriscore-2021-different-from-2023",
    "en:nutriscore-2021-better-than-2023",
    "en:nutriscore-2021-b-2023-c",
    "en:packagings-complete",
    "en:packagings-not-empty",
    "en:ecoscore-extended-data-not-computed",
    "en:ecoscore-computed",
    "en:ecoscore-changed",
    "en:ecoscore-grade-changed",
  ],
  no_nutrition_data: "",
  nova_group: 3,
  nova_group_debug: "",
  nova_groups: "3",
  nova_groups_markers: {
    "3": [["ingredients", "en:salt"]],
  },
  nova_groups_tags: ["en:3-processed-foods"],
  nucleotides_tags: [],
  nutrient_levels: {
    fat: "low",
    salt: "low",
    "saturated-fat": "low",
    sugars: "low",
  },
  nutrient_levels_tags: [
    "en:fat-in-low-quantity",
    "en:saturated-fat-in-low-quantity",
    "en:sugars-in-low-quantity",
    "en:salt-in-low-quantity",
  ],
  nutriments: {
    carbohydrates: 7.4,
    carbohydrates_100g: 7.4,
    carbohydrates_unit: "g",
    carbohydrates_value: 7.4,
    energy: 159,
    "energy-kcal": 38,
    "energy-kcal_100g": 38,
    "energy-kcal_unit": "kcal",
    "energy-kcal_value": 38,
    "energy-kcal_value_computed": 37.9,
    energy_100g: 159,
    energy_unit: "kcal",
    energy_value: 38,
    fat: 0.7,
    fat_100g: 0.7,
    fat_unit: "g",
    fat_value: 0.7,
    "fruits-vegetables-legumes-estimate-from-ingredients_100g": 0,
    "fruits-vegetables-legumes-estimate-from-ingredients_serving": 0,
    "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
    "fruits-vegetables-nuts-estimate-from-ingredients_serving": 0,
    "nova-group": 3,
    "nova-group_100g": 3,
    "nova-group_serving": 3,
    "nutrition-score-fr": 0,
    "nutrition-score-fr_100g": 0,
    proteins: 0.5,
    proteins_100g: 0.5,
    proteins_unit: "g",
    proteins_value: 0.5,
    salt: 0.1,
    salt_100g: 0.1,
    salt_unit: "g",
    salt_value: 0.1,
    "saturated-fat": 0.1,
    "saturated-fat_100g": 0.1,
    "saturated-fat_unit": "g",
    "saturated-fat_value": 0.1,
    sodium: 0.04,
    sodium_100g: 0.04,
    sodium_unit: "g",
    sodium_value: 0.04,
    sugars: 1.8,
    sugars_100g: 1.8,
    sugars_unit: "g",
    sugars_value: 1.8,
  },
  nutriscore: {
    "2021": {
      category_available: 1,
      data: {
        energy: 159,
        energy_points: 0,
        energy_value: 159,
        fiber: 0,
        fiber_points: 0,
        fiber_value: 0,
        fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
        fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
        fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
        is_beverage: 0,
        is_cheese: 0,
        is_fat: 0,
        is_water: 0,
        negative_points: 0,
        positive_points: 0,
        proteins: 0.5,
        proteins_points: 0,
        proteins_value: 0.5,
        saturated_fat: 0.1,
        saturated_fat_points: 0,
        saturated_fat_value: 0.1,
        sodium: 40,
        sodium_points: 0,
        sodium_value: 40,
        sugars: 1.8,
        sugars_points: 0,
        sugars_value: 1.8,
      },
      grade: "b",
      nutrients_available: 1,
      nutriscore_applicable: 1,
      nutriscore_computed: 1,
      score: 0,
    },
    "2023": {
      category_available: 1,
      data: {
        components: {
          negative: [
            {
              id: "energy",
              points: 3,
              points_max: 10,
              unit: "kJ",
              value: 159,
            },
            {
              id: "sugars",
              points: 1,
              points_max: 10,
              unit: "g",
              value: 1.8,
            },
            {
              id: "saturated_fat",
              points: 0,
              points_max: 10,
              unit: "g",
              value: 0.1,
            },
            {
              id: "salt",
              points: 0,
              points_max: 20,
              unit: "g",
              value: 0.1,
            },
            {
              id: "non_nutritive_sweeteners",
              points: 0,
              points_max: null,
              unit: null,
              value: 0,
            },
          ],
          positive: [
            {
              id: "proteins",
              points: 0,
              points_max: 7,
              unit: "g",
              value: 0.5,
            },
            {
              id: "fiber",
              points: 0,
              points_max: 5,
              unit: "g",
              value: 0,
            },
            {
              id: "fruits_vegetables_legumes",
              points: 0,
              points_max: 6,
              unit: "%",
              value: 0,
            },
          ],
        },
        count_proteins: 1,
        count_proteins_reason: "beverage",
        is_beverage: 1,
        is_cheese: 0,
        is_fat_oil_nuts_seeds: 0,
        is_red_meat_product: 0,
        is_water: 0,
        negative_points: 4,
        negative_points_max: 50,
        non_nutritive_sweeteners_max: 4,
        positive_nutrients: ["proteins", "fiber", "fruits_vegetables_legumes"],
        positive_points: 0,
        positive_points_max: 18,
      },
      grade: "c",
      nutrients_available: 1,
      nutriscore_applicable: 1,
      nutriscore_computed: 1,
      score: 4,
    },
  },
  nutriscore_2021_tags: ["b"],
  nutriscore_2023_tags: ["c"],
  nutriscore_data: {
    energy: 159,
    energy_points: 0,
    energy_value: 159,
    fiber: 0,
    fiber_points: 0,
    fiber_value: 0,
    fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
    fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
    fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
    grade: "b",
    is_beverage: 0,
    is_cheese: 0,
    is_fat: 0,
    is_water: 0,
    negative_points: 0,
    positive_points: 0,
    proteins: 0.5,
    proteins_points: 0,
    proteins_value: 0.5,
    saturated_fat: 0.1,
    saturated_fat_points: 0,
    saturated_fat_value: 0.1,
    score: 0,
    sodium: 40,
    sodium_points: 0,
    sodium_value: 40,
    sugars: 1.8,
    sugars_points: 0,
    sugars_value: 1.8,
  },
  nutriscore_grade: "b",
  nutriscore_score: 0,
  nutriscore_score_opposite: 0,
  nutriscore_tags: ["b"],
  nutriscore_version: "2021",
  nutrition_data: "on",
  nutrition_data_per: "100g",
  nutrition_data_prepared: "",
  nutrition_data_prepared_per: "100g",
  nutrition_grade_fr: "b",
  nutrition_grades: "b",
  nutrition_grades_tags: ["b"],
  nutrition_score_beverage: 0,
  nutrition_score_debug: "",
  nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients: 1,
  nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_value: 0,
  nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients: 1,
  nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value: 0,
  nutrition_score_warning_no_fiber: 1,
  obsolete: "",
  obsolete_since_date: "",
  origin: "",
  origin_da: "",
  origin_de: "",
  origin_en: "",
  origin_fr: "",
  origins: "Finland",
  origins_hierarchy: ["en:finland"],
  origins_lc: "en",
  origins_tags: ["en:finland"],
  other_nutritional_substances_tags: [],
  packaging_materials_tags: ["en:hdpe-2-high-density-polyethylene", "en:tetra-pak"],
  packaging_recycling_tags: [],
  packaging_shapes_tags: ["en:bottle-cap", "en:brick"],
  packaging_text: "",
  packaging_text_da: "",
  packaging_text_de: "",
  packaging_text_en: "",
  packaging_text_fr: "",
  packagings: [
    {
      material: "en:tetra-pak",
      number_of_units: 1,
      shape: "en:brick",
    },
    {
      material: "en:hdpe-2-high-density-polyethylene",
      number_of_units: 1,
      shape: "en:bottle-cap",
    },
  ],
  packagings_complete: 1,
  packagings_materials: {
    all: {},
    "en:plastic": {},
    "en:unknown": {},
  },
  packagings_n: 2,
  photographers_tags: ["kiliweb", "grumpf", "moon-rabbit"],
  pnns_groups_1: "Beverages",
  pnns_groups_1_tags: ["beverages", "known"],
  pnns_groups_2: "Plant-based milk substitutes",
  pnns_groups_2_tags: ["plant-based-milk-substitutes", "known"],
  popularity_key: 13,
  popularity_tags: [
    "top-75-percent-scans-2023",
    "top-80-percent-scans-2023",
    "top-85-percent-scans-2023",
    "top-90-percent-scans-2023",
    "top-50000-de-scans-2023",
    "top-100000-de-scans-2023",
    "top-country-de-scans-2023",
  ],
  product_name: "Aito Oat Drink Natural",
  product_name_da: "",
  product_name_de: "Aito Oat Drink Natural",
  product_name_en: "",
  product_name_fr: "Oat drink natural",
  product_quantity: "1000",
  product_quantity_unit: "ml",
  purchase_places: "",
  purchase_places_tags: [],
  quantity: "1 L",
  removed_countries_tags: [],
  rev: 30,
  scans_n: 1,
  selected_images: {
    front: {
      display: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.400.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.400.jpg",
      },
      small: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.200.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.200.jpg",
      },
      thumb: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_de.19.100.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/front_fr.3.100.jpg",
      },
    },
    ingredients: {
      display: {
        da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.400.jpg",
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.400.jpg",
        en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.400.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.400.jpg",
      },
      small: {
        da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.200.jpg",
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.200.jpg",
        en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.200.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.200.jpg",
      },
      thumb: {
        da: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_da.26.100.jpg",
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_de.21.100.jpg",
        en: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_en.25.100.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/ingredients_fr.24.100.jpg",
      },
    },
    nutrition: {
      display: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.400.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.400.jpg",
      },
      small: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.200.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.200.jpg",
      },
      thumb: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_de.23.100.jpg",
        fr: "https://images.openfoodfacts.org/images/products/641/022/200/5402/nutrition_fr.5.100.jpg",
      },
    },
    packaging: {
      display: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.400.jpg",
      },
      small: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.200.jpg",
      },
      thumb: {
        de: "https://images.openfoodfacts.org/images/products/641/022/200/5402/packaging_de.27.100.jpg",
      },
    },
  },
  states:
    "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-completed, en:characteristics-to-be-completed, en:origins-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:packaging-photo-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded",
  states_hierarchy: [
    "en:to-be-completed",
    "en:nutrition-facts-completed",
    "en:ingredients-completed",
    "en:expiration-date-to-be-completed",
    "en:packaging-code-completed",
    "en:characteristics-to-be-completed",
    "en:origins-completed",
    "en:categories-completed",
    "en:brands-completed",
    "en:packaging-to-be-completed",
    "en:quantity-completed",
    "en:product-name-completed",
    "en:photos-validated",
    "en:packaging-photo-selected",
    "en:nutrition-photo-selected",
    "en:ingredients-photo-selected",
    "en:front-photo-selected",
    "en:photos-uploaded",
  ],
  states_tags: [
    "en:to-be-completed",
    "en:nutrition-facts-completed",
    "en:ingredients-completed",
    "en:expiration-date-to-be-completed",
    "en:packaging-code-completed",
    "en:characteristics-to-be-completed",
    "en:origins-completed",
    "en:categories-completed",
    "en:brands-completed",
    "en:packaging-to-be-completed",
    "en:quantity-completed",
    "en:product-name-completed",
    "en:photos-validated",
    "en:packaging-photo-selected",
    "en:nutrition-photo-selected",
    "en:ingredients-photo-selected",
    "en:front-photo-selected",
    "en:photos-uploaded",
  ],
  stores: "",
  stores_tags: [],
  teams: "pain-au-chocolat",
  teams_tags: ["pain-au-chocolat"],
  traces: "",
  traces_from_ingredients: "",
  traces_from_user: "(en) ",
  traces_hierarchy: [],
  traces_lc: "en",
  traces_tags: [],
  unique_scans_n: 1,
  unknown_ingredients_n: 1,
  unknown_nutrients_tags: [],
  update_key: "20240209",
  vitamins_tags: [],
  weighers_tags: [],
  weighters_tags: [],
}
