import { z } from "zod"

export const productSchema = z.object({
  barcode_number: z.string(),
  barcode_formats: z.string(),
  mpn: z.string(),
  model: z.string(),
  asin: z.string(),
  title: z.string(),
  category: z.string(),
  manufacturer: z.string(),
  brand: z.string(),
  age_group: z.string(),
  ingredients: z.string(),
  nutrition_facts: z.string(),
  energy_efficiency_class: z.string(),
  color: z.string(),
  gender: z.string(),
  material: z.string(),
  pattern: z.string(),
  format: z.string(),
  multipack: z.string(),
  size: z.string(),
  length: z.string(),
  width: z.string(),
  height: z.string(),
  weight: z.string(),
  release_date: z.string(),
  description: z.string(),
  features: z.array(z.unknown()),
  images: z.array(z.string()),
  last_update: z.string(),
  stores: z.array(
    z.object({
      name: z.string(),
      country: z.string(),
      currency: z.string(),
      currency_symbol: z.string(),
      price: z.string(),
      sale_price: z.string(),
      tax: z.array(z.unknown()),
      link: z.string(),
      item_group_id: z.string(),
      availability: z.string(),
      condition: z.string(),
      shipping: z.array(z.unknown()),
      last_update: z.string(),
    })
  ),
})

export type ProductSchema = z.infer<typeof productSchema>
